### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by wezleytsai** [the-ninja-turtles/turtle#76]
- Step by step instructions to run app
- Mention Auth0 requirement
- Mention ES6 and IO.js
- Screenshot of UI (when finished)
- Link to MICROSERVICE.md STYLEGUIDE.md and CONTRIBUTION.md and

**Comment by azangru** [comment]
I guess this is what cshep wrote:

Turtle

https://github.com/the-ninja-turtles/turtle

Update README!
installation instructions, the simplest list of steps to get running
other major pieces of software required (postgres? memcached? docker? etc.)
version of node required?
link to deployed demo
screenshots?
who you are / why you’re doing it (bonus)

Good Documentation!
MICROSERVICES and CONTRIBUTING are well done
always good to see a STYLE GUIDE!
